FROM nginx
ARG ESPN_LEAGUE_ID
ENV REACT_APP_ESPN_LEAGUE_ID=${ESPN_LEAGUE_ID}

ARG ESPN_API_S2
ENV REACT_APP_ESPN_API_S2=${ESPN_API_S2}

ARG ESPN_API_SWID
ENV REACT_APP_ESPN_API_SWID=${ESPN_API_SWID}

ARG STRAPI_URL
ENV REACT_APP_STRAPI_URL=${STRAPI_URL}

ARG STRAPI_USERNAME
ENV REACT_APP_STRAPI_USERNAME=${STRAPI_USERNAME}

ARG STRAPI_PASSWORD
ENV REACT_APP_STRAPI_PASSWORD=${STRAPI_PASSWORD}

COPY build /usr/share/nginx/html
